// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace HadithBooks
{
	public partial class BookCell : UITableViewCell
	{
		public BookCell() : base()
		{
		}
		public BookCell (IntPtr handle) : base (handle)
		{
		}
	}
}
