// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace HadithBooks
{
	public partial class BookPageViewController : UIViewController
	{
		public BookPageViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
